events {}

http {
    server {
        listen 3000;

        location / {
            root /usr/share/nginx/html;
            index index.html;
        }

        location /api {
            resolver 127.0.0.11;
            proxy_pass http://component1:8000;
        }
    }
}
